export const userSettingsDefaults = {
    updatedAt: null as Date | null,
    showPrivateSetups: true,
    publicFollowees: true,
    publicBookmarks: false,
    notifSiteEnabled: true,
    notifSiteFollowed: true,
    notifSiteFolloweePost: true,
    notifSiteCoauthorAdded: true,
    notifPushFollowed: true,
    notifPushFolloweePost: true,
    notifPushCoauthorAdded: true,
    notifWebhookEnabled: false,
    notifWebhookUrl: null,
    notifWebhookFollowed: true,
    notifWebhookFolloweePost: true,
    notifWebhookCoauthorAdded: true,
    showNSFW: false,
}
