name: Release

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - 'release/v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-pr:
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: danielroe/uppt@7bcfb5397c37202ef882363f755423130419d28a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release-tag:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v') && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: danielroe/uppt@7bcfb5397c37202ef882363f755423130419d28a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
